# Generated by Django 5.2.9 on 2026-01-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='', max_length=1000)),
                ('skills', models.CharField(default='', max_length=1000)),
                ('experience', models.CharField(default='', max_length=1000)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('major', models.CharField(default='---', max_length=200)),
                ('address', models.CharField(default='---', max_length=200)),
                ('active_connections', models.IntegerField(default=0)),
                ('total_msg', models.IntegerField(default=5)),
                ('remain_msg', models.IntegerField(default=5)),
                ('reviews', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
