# Generated by Django 5.2.9 on 2026-01-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profileImage/about.jpg', upload_to='profileImage/'),
        ),
    ]
