# Generated by Django 5.2.9 on 2026-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermd',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
