# Generated by Django 5.2.9 on 2026-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect_app', '0002_alter_usermd_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
